### ISSUE TITLE
issues found! display file #HackaIran.txt

### ISSUE THREAD

**Issue by yonesb9** [HackaIran/HackaLottery#1]
Hey, I need help
How to display file #HackaIran.txt on home screen?
I see a problem at this file address but I don't know how to fix it!
-- routes/index.js --> Line: 4 to 7
[https://github.com/HackaIran/HackaLottery/blob/master/routes/index.js](url)
Thank you (^_^).

**Comment by Alireza29675** [comment]
Hey Yones,

I hope you're doing great!

Can you provide more details about the error/problem you see at `routes/index.js`?

**Comment by yonesb9** [comment]
hey again
The project is running but the users file is not displayed and I think the problem is with the index.js file!
All I have is a problem that users can' display and I want to randomly Lottery!
[http://s7.picofile.com/file/8384040050/hl.png](url)
[http://s7.picofile.com/file/8384040192/hlc.png](url)

**Comment by Alireza29675** [comment]
Yones,
I assessed the code and it seems it's not the final code that is uploaded! Please look for the alternatives and we'll try to fix this as soon as it's possible.
Thank you for the report.

**Comment by Alireza29675** [comment]
@yonesb9
Check this issue out, we look after what you reported: #2
